import Head from 'next/head'

import { useQueryState } from 'nuqs'

export default function Home() {
  const [search, setSearch] = useQueryState('search', {
    defaultValue: '',
    clearOnDefault: true,
  })
  return (
    <>
      <Head>
        <title>nuqs-640 repro</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <input
        type="search"
        value={search}
        onChange={(e) => setSearch(e.target.value)}
      />
    </>
  )
}
